name: Deploy to Amazon ECR
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-push:
    name: Build and Push to Amazon ECR
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2 # or your AWS region
 
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          # Ensure we're using the ECR Public login endpoint
          registry-type: public
 
      - name: Build, tag, and push image to Amazon ECR Public
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          ECR_REPOSITORY: aman4 # your ECR public repository name
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and push it to ECR so that it can
          # be deployed to ECS. Make sure you're using the correct URI for the public registry.
          docker build -t public.ecr.aws/p6v8j1i8/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push public.ecr.aws/p6v8j1i8/$ECR_REPOSITORY:$IMAGE_TAG
          # If you want to use the 'latest' tag, you can also push that.
          docker tag public.ecr.aws/p6v8j1i8/$ECR_REPOSITORY:$IMAGE_TAG public.ecr.aws/p6v8j1i8/$ECR_REPOSITORY:latest
          docker push public.ecr.aws/p6v8j1i8/$ECR_REPOSITORY:latest
